// src/renderer/src/components/ui/button.tsx
import * as React from 'react'
import { Slot } from '@radix-ui/react-slot'
import { cva, type VariantProps } from 'class-variance-authority'

import { cn } from '@/lib/utils'

const buttonVariants = cva(
  'inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0',
  {
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:bg-primary/90',
        destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90',
        outline: 'border border-input bg-background hover:bg-accent hover:text-accent-foreground',
        secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
        ghost: 'hover:bg-accent hover:text-accent-foreground',
        link: 'text-primary underline-offset-4 hover:underline'
      },
      size: {
        default: 'h-10 px-4 py-2',
        sm: 'h-9 rounded-md px-3',
        lg: 'h-11 rounded-md px-8',
        icon: 'h-10 w-10'
      }
    },
    defaultVariants: {
      variant: 'default',
      size: 'default'
    }
  }
)

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : 'button'
    return (
      <Comp className={cn(buttonVariants({ variant, size, className }))} ref={ref} {...props} />
    )
  }
)
Button.displayName = 'Button'

export { Button }

// src/renderer/src/components/design-system/Button.vue
<template>
  <button :class="buttonClasses" :disabled="disabled" :type="type" @click="handleClick">
    <Icon v-if="icon && iconPosition === 'left'" :name="icon" :size="iconSize" class="mr-2" />

    <span v-if="$slots.default" class="button-content">
      <slot />
    </span>

    <Icon v-if="icon && iconPosition === 'right'" :name="icon" :size="iconSize" class="ml-2" />

    <Icon
      v-if="loading"
      name="loader-2"
      :size="iconSize"
      class="animate-spin"
      :class="{ 'ml-2': $slots.default }"
    />
  </button>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { cn, getButtonVariantClasses, getComponentSizeClasses } from '@renderer/utils/design-system'
import Icon from './Icon.vue'

export interface ButtonProps {
  variant?: 'primary' | 'secondary' | 'text' | 'outlined' | 'destructive'
  size?: 'sm' | 'md' | 'lg'
  type?: 'button' | 'submit' | 'reset'
  disabled?: boolean
  loading?: boolean
  icon?: string
  iconPosition?: 'left' | 'right'
  fullWidth?: boolean
  className?: string
}

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'primary',
  size: 'md',
  type: 'button',
  disabled: false,
  loading: false,
  iconPosition: 'left',
  fullWidth: false
})

const emit = defineEmits<{
  click: [event: MouseEvent]
}>()

const iconSize = computed(() => {
  const sizeMap = {
    sm: 16,
    md: 20,
    lg: 24
  }
  return sizeMap[props.size]
})

const buttonClasses = computed(() => {
  const baseClasses = [
    // 基础样式
    'inline-flex items-center justify-center',
    'font-medium rounded-sm',
    'transition-all duration-fast ease-material-standard',
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
    'disabled:pointer-events-none disabled:opacity-50',

    // 变体样式
    getButtonVariantClasses(props.variant),

    // 尺寸样式
    getComponentSizeClasses(props.size).padding,
    getComponentSizeClasses(props.size).height,

    // 条件样式
    {
      'w-full': props.fullWidth,
      'cursor-not-allowed': props.disabled,
      'cursor-wait': props.loading
    }
  ]

  return cn(baseClasses, props.className)
})

const handleClick = (event: MouseEvent) => {
  if (!props.disabled && !props.loading) {
    emit('click', event)
  }
}
</script>

<style scoped>
.button-content {
  @apply flex items-center;
}

/* 按钮涟漪效果 */
button {
  position: relative;
  overflow: hidden;
}

button::before {
  content: '';
  position: absolute;
  top: 50%;
  left: 50%;
  width: 0;
  height: 0;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.3);
  transform: translate(-50%, -50%);
  transition:
    width 0.3s ease,
    height 0.3s ease;
}

button:active::before {
  width: 300px;
  height: 300px;
}

/* 深色模式下的涟漪效果 */
.dark button::before {
  background: rgba(0, 0, 0, 0.2);
}
</style>
